#!/usr/bin/env bash
# Seed every secret into Vault dev so the stack can resolve them at startup.
# Secrets: LLM API key, tracing backend key, JWT signing key, DB password,
# MinIO credentials. This is the ONLY place secrets are written; nothing is
# committed. Run once after `vault` is up (invoked from compose or by hand).
set -euo pipefail

# TODO: vault kv put secret/llm api_key=...
# TODO: vault kv put secret/tracing key=...
# TODO: vault kv put secret/jwt signing_key=...
# TODO: vault kv put secret/db password=...
# TODO: vault kv put secret/minio access_key=... secret_key=...
echo "TODO: implement Vault secret seeding"
